apiVersion: v1
kind: PersistentVolume
metadata:
  name: pvc-jenkins
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 8Gi
  nfs:
    path: /data/jenkins
    server: k8s-3
  persistentVolumeReclaimPolicy: Delete
  storageClassName: nfs-client
  volumeMode: Filesystem
