- name: Create a k8s env namespace
  k8s:
    name: "argocd"
    api_version: v1
    kind: Namespace
    state: present

- name: Install through manifest
  kubernetes.core.k8s:
    state: present
    src: https://raw.githubusercontent.com/argoproj/argo-cd/stable/manifests/install.yaml


#kubectl -n argocd get secret argocd-initial-admin-secret -o jsonpath='{.data.password}' | base64 -d