- name: Copy the argocd values file based on the deployment
  template:
    src: argocd-values.yml.j2
    dest: argocd-values.yml

- name: Create a k8s env namespace
  k8s:
    name: "argocd"
    api_version: v1
    kind: Namespace
    state: present

- name: Helm repo add
  command: helm repo add argo https://argoproj.github.io/argo-helm

- name: Helm repo update
  command: helm repo update

- name: Init ArgoCD
  command: >
    helm upgrade -i --history-max=1 \
    argocd \
    --namespace argocd \
    -f argocd-values.yml \
    argo/argo-cd
