- name: Create a k8s env namespace
  k8s:
    name: "nginx-ingress"
    api_version: v1
    kind: Namespace
    state: present


- name: Install ingress
  command: >
    helm upgrade -i --history-max=1 \
    nginx-ingress \
    roles/ingress/templates/helm-chart \
    --namespace nginx-ingress \
    -f roles/ingress/files/ingress-values.yaml


- name: Apply K8s resources
  k8s:
    definition: "{{ lookup('template', '{{ item }}') | from_yaml }}"
  with_fileglob:
    - "ing-*.yml"
