- name: Create a k8s env namespace
  k8s:
    name: "jenkins"
    api_version: v1
    kind: Namespace
    state: present

- name: Render k8s jenkins values template
  template:
    src: jenkins-values.yml.j2
    dest: jenkins-values.yml

- name: Apply pvc
  kubernetes.core.k8s:
    state: present
    src: jenkins-pv.yml


- name: Helm repo add
  command: helm repo add jenkins https://charts.jenkins.io

- name: Helm repo update
  command: helm repo update

- name: Init jenkins
  command: > 
    helm upgrade -i --history-max=1 \
    jenkins \
    --namespace jenkins \
    -f jenkins-values.yml  \
    jenkins/jenkins

#$ kubectl exec --namespace jenkins -it jenkins -c jenkins -- /bin/cat /run/secrets/chart-admin-password && echo
