- name: Create a k8s env namespace
  k8s:
    name: "harbor"
    api_version: v1
    kind: Namespace
    state: present

- name: Render k8s harbor values template
  template:
    src: harbor-values.yml.j2
    dest: harbor-values.yml

- name: Helm repo add
  command: helm repo add harbor https://helm.goharbor.io

- name: Helm repo update
  command: helm repo update

- name: Init harbor
  command: >
    helm upgrade -i --history-max=1 \
    harbor \
    --namespace harbor \
    -f harbor-values.yml  \
    harbor/harbor
